<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Theme {
	private $theme_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'theme_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'theme_page_init' ) );
	}

	public function theme_add_plugin_page() {
		add_menu_page(
			'theme', // page_title
			'お客様情報', // menu_title
			'manage_options', // capability
			'theme', // menu_slug
			array( $this, 'theme_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			3 // position
		);
	}

	public function theme_create_admin_page() {
		$this->theme_options = get_option( 'theme_option_name' ); ?>

		<div class="wrap">
			<h2>お客様情報</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'theme_option_group' );
					do_settings_sections( 'theme-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function theme_page_init() {
		register_setting(
			'theme_option_group', // option_group
			'theme_option_name', // option_name
			array( $this, 'theme_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'theme_setting_section', // id
			'', // title
			array( $this, 'theme_section_info' ), // callback
			'theme-admin' // page
		);

		add_settings_field(
			'op_0', // id
			'施設名', // title
			array( $this, 'op_0_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_1', // id
			'園長', // title
			array( $this, 'op_1_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_2', // id
			'種別', // title
			array( $this, 'op_2_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_3', // id
			'設立', // title
			array( $this, 'op_3_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_4', // id
			'郵便番号', // title
			array( $this, 'op_4_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_5', // id
			'所在地', // title
			array( $this, 'op_5_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_6', // id
			'定員', // title
			array( $this, 'op_6_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_7', // id
			'TEL', // title
			array( $this, 'op_7_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_8', // id
			'FAX', // title
			array( $this, 'op_8_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_9', // id
			'保育時間（平日）', // title
			array( $this, 'op_9_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_10', // id
			'保育時間（休日）', // title
			array( $this, 'op_10_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_11', // id
			'メールアドレス', // title
			array( $this, 'op_11_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_12', // id
			'アクセス', // title
			array( $this, 'op_12_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

	}

	public function theme_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['op_0'] ) ) {
			$sanitary_values['op_0'] = sanitize_text_field( $input['op_0'] );
		}

		if ( isset( $input['op_1'] ) ) {
			$sanitary_values['op_1'] = sanitize_text_field( $input['op_1'] );
		}

		if ( isset( $input['op_2'] ) ) {
			$sanitary_values['op_2'] = sanitize_text_field( $input['op_2'] );
		}

		if ( isset( $input['op_3'] ) ) {
			$sanitary_values['op_3'] = sanitize_text_field( $input['op_3'] );
		}

		if ( isset( $input['op_4'] ) ) {
			$sanitary_values['op_4'] = sanitize_text_field( $input['op_4'] );
		}

		if ( isset( $input['op_5'] ) ) {
			$sanitary_values['op_5'] = sanitize_text_field( $input['op_5'] );
		}

		if ( isset( $input['op_6'] ) ) {
			$sanitary_values['op_6'] = sanitize_text_field( $input['op_6'] );
		}

		if ( isset( $input['op_7'] ) ) {
			$sanitary_values['op_7'] = sanitize_text_field( $input['op_7'] );
		}

		if ( isset( $input['op_8'] ) ) {
			$sanitary_values['op_8'] = sanitize_text_field( $input['op_8'] );
		}

		if ( isset( $input['op_9'] ) ) {
			$sanitary_values['op_9'] = sanitize_text_field( $input['op_9'] );
		}

		if ( isset( $input['op_10'] ) ) {
			$sanitary_values['op_10'] = sanitize_text_field( $input['op_10'] );
		}

		if ( isset( $input['op_11'] ) ) {
			$sanitary_values['op_11'] = sanitize_text_field( $input['op_11'] );
		}

		if ( isset( $input['op_12'] ) ) {
			$sanitary_values['op_12'] = sanitize_text_field( $input['op_12'] );
		}

		return $sanitary_values;
	}

	public function theme_section_info() {

	}

	public function op_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_0]" id="op_0" value="%s">',
			isset( $this->theme_options['op_0'] ) ? esc_attr( $this->theme_options['op_0']) : ''
		);
	}

	public function op_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_1]" id="op_1" value="%s">',
			isset( $this->theme_options['op_1'] ) ? esc_attr( $this->theme_options['op_1']) : ''
		);
	}

	public function op_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_2]" id="op_2" value="%s">',
			isset( $this->theme_options['op_2'] ) ? esc_attr( $this->theme_options['op_2']) : ''
		);
	}

	public function op_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_3]" id="op_3" value="%s">',
			isset( $this->theme_options['op_3'] ) ? esc_attr( $this->theme_options['op_3']) : ''
		);
	}

	public function op_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_4]" id="op_4" value="%s">',
			isset( $this->theme_options['op_4'] ) ? esc_attr( $this->theme_options['op_4']) : ''
		);
	}

	public function op_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_5]" id="op_5" value="%s">',
			isset( $this->theme_options['op_5'] ) ? esc_attr( $this->theme_options['op_5']) : ''
		);
	}

	public function op_6_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_6]" id="op_6" value="%s">',
			isset( $this->theme_options['op_6'] ) ? esc_attr( $this->theme_options['op_6']) : ''
		);
	}

	public function op_7_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_7]" id="op_7" value="%s">',
			isset( $this->theme_options['op_7'] ) ? esc_attr( $this->theme_options['op_7']) : ''
		);
	}

	public function op_8_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_8]" id="op_8" value="%s">',
			isset( $this->theme_options['op_8'] ) ? esc_attr( $this->theme_options['op_8']) : ''
		);
	}

	public function op_9_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_9]" id="op_9" value="%s">',
			isset( $this->theme_options['op_9'] ) ? esc_attr( $this->theme_options['op_9']) : ''
		);
	}

	public function op_10_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_10]" id="op_10" value="%s">',
			isset( $this->theme_options['op_10'] ) ? esc_attr( $this->theme_options['op_10']) : ''
		);
	}

	public function op_11_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_11]" id="op_11" value="%s">',
			isset( $this->theme_options['op_11'] ) ? esc_attr( $this->theme_options['op_11']) : ''
		);
	}

	public function op_12_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_12]" id="op_12" value="%s">',
			isset( $this->theme_options['op_12'] ) ? esc_attr( $this->theme_options['op_12']) : ''
		);
	}

}
if ( is_admin() )
	$theme = new Theme();

/*
 * Retrieve this value with:
 * $theme_options = get_option( 'theme_option_name' ); // Array of All Options
 * $op_0 = $theme_options['op_0']; // op
 * $op_1 = $theme_options['op_1']; // op
 * $op_2 = $theme_options['op_2']; // op
 * $op_3 = $theme_options['op_3']; // op
 * $op_4 = $theme_options['op_4']; // op
 * $op_5 = $theme_options['op_5']; // op
 * $op_6 = $theme_options['op_6']; // op
 * $op_7 = $theme_options['op_7']; // op
 * $op_8 = $theme_options['op_8']; // op
 * $op_9 = $theme_options['op_9']; // op
 * $op_10 = $theme_options['op_10']; // op
 * $op_11 = $theme_options['op_11']; // op
 */
